//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework2Part3Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int Grade_ID { get; set; }
        public Nullable<int> Student_ID { get; set; }
        public Nullable<int> Subject_ID { get; set; }
        public Nullable<int> Grade_Mark { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
